import { z } from 'zod';

export const ArtifactRefSchema = z.object({
  path: z.string().describe('File path relative to workspace root'),
  reason: z.string().describe('Why this file is relevant to the review'),
  priority: z.enum(['high', 'medium', 'low']).describe('Review priority level'),
});

export type ArtifactRef = z.infer<typeof ArtifactRefSchema>;

/**
 * Reviewer config schema — shared across all review tools.
 * Allows per-request override of provider, model, and generation parameters.
 */
export const ReviewerConfigSchema = z.object({
  provider: z
    .enum(['openai', 'anthropic', 'google', 'openrouter', 'compatible'])
    .optional()
    .describe('Review provider. Default: env REVIEW_PROVIDER or "openai".'),
  model: z
    .string()
    .optional()
    .describe('Model to use. Default: env REVIEW_MODEL or provider default.'),
  base_url: z
    .string()
    .optional()
    .describe('Custom API base URL (for compatible/self-hosted providers).'),
  api_key: z
    .string()
    .optional()
    .describe('Per-request API key. Overrides env-based key resolution. Useful for compatible/self-hosted providers.'),
  temperature: z
    .number()
    .min(0)
    .max(2)
    .optional()
    .describe('Sampling temperature override. Default: 0.2.'),
  top_p: z
    .number()
    .min(0)
    .max(1)
    .optional()
    .describe('Top-p override. Default: 0.1.'),
}).describe('Per-request reviewer configuration override.');

export type ReviewerConfig = z.infer<typeof ReviewerConfigSchema>;

/**
 * Iteration tracking fields — added to MCP output (not sent to the reviewer model).
 */
export const IterationMetaOutputSchema = z.object({
  iteration_count: z.number().describe('Current iteration number (1-based) as reported by the caller.'),
  iteration_limit: z.number().describe('Maximum iterations allowed for this phase.'),
  iteration_limit_reached: z.boolean().describe('Whether the iteration limit has been reached.'),
});

/**
 * Token usage fields — added to MCP output for cost/usage tracking.
 */
export const TokenUsageOutputSchema = z.object({
  token_usage: z.object({
    input_tokens: z.number().describe('Total input tokens consumed by the reviewer'),
    output_tokens: z.number().describe('Total output tokens generated by the reviewer'),
    total_tokens: z.number().describe('Sum of input + output tokens'),
    api_calls: z.number().describe('Number of API calls made (1 + tool loop rounds)'),
    provider: z.string().describe('Provider used (openai, anthropic, google, etc.)'),
    model: z.string().describe('Model used for the review'),
    estimated_cost_usd: z.number().nullable().describe('Estimated cost in USD based on model pricing (null if pricing unknown)'),
  }).describe('Token usage and estimated cost for this review call'),
});
